### ISSUE TITLE
Switching order of players bug.

### ISSUE THREAD

**Issue by alexjmak** [malikh22/ShogiCS301#6] opened 2020-04-21 03:39 UTC
(Minor / Other) If I switch the order of players such that the first player is the Dumb Computer Player and the second player is the Human player, I cannot make moves.

**Comment by faker20** [comment] 2020-04-27 22:25
Issue caused by legalMoveList restriction. Only run when playerNum is 0. Now fixed.

**Closed as completed by faker20** 2020-04-27 22:25 UTC

**Comment by malikh22** [comment] 2020-04-29 17:31
Not entirely fixed. Just recommend always playing as Player 0 (see game manual)

**Comment by alexjmak** [comment] 2020-04-29 17:47
Ok, thanks for the update.
